### PR TITLE
Version upgrades to fix gpu build

### PR DESCRIPTION
**Pull request by maxpumperla**
#115 surfaces a little bug that's fixed here. however, when inspecting the gpu build after the bug fix, it became apparent we had to bump to javacpp `1.5.2` to avoid version conflicts in `konduit-serving-gpu/pom.xml`. As a consequence some other dependencies had to be upgraded as well. two problems:

- javacpp TF 1.15 doesn't seem to come with `dtypes`  anymore. `GraphRunner` suffers from this.
- `GpuMetrics` as on current master doesn't compile.

@agibsonccc I think I need your input here on how to proceed. In particular, I wasn't aware that `GraphRunner` is somewhat of a copy of what we have in nd4j... how can we avoid this in the first place, going forward?

### CODE REVIEW

**Comment by maxpumperla** [comment]
@ShamsUlAzeem also if you see another way to avoid these conflicts, please let me know. thing is, at some point we have to upgrade this anyway and right now the GPU build is broken.

**Comment by ShamsUlAzeem** [comment]
I haven't played around with the GPU build much. @agibsonccc would know better about that. I recall we were waiting for some changes in dl4j so the GPU build could be fixed. I haven't followed up on that with adam.

**Comment by ShamsUlAzeem** [comment]
I think we can still stick with javacpp 1.5.1 for the GPU build

**Comment by ShamsUlAzeem** [comment]
@maxpumperla the build passed for me for GPU with javacpp 1.5.1. There were a couple of enforcement rules issue, apart from that the build completes. The command I used was the following: 
```
"mvn clean install -P gpu,war,test,converter,python,pmml,uberjar -Dchip=gpu -Djavacpp.platform=windows-x86_64 -DskipTests=true
```

The tests need to be taken a look at though. For the `GpuMetricsTest` I keep getting the following error

```
java.lang.UnsatisfiedLinkError: no jnicudart in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1483)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1186)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
	at org.bytedeco.cuda.global.cudart.<clinit>(cudart.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
	at org.bytedeco.cuda.global.nvml.<clinit>(nvml.java:15)
	at ai.konduit.serving.gpu.GpuMetrics.bindTo(GpuMetrics.java:56)
	at ai.konduit.serving.gpu.GpuMetricsTest.testMetrics(GpuMetricsTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.UnsatisfiedLinkError: no cudart in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1483)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1137)
	... 31 more
```

**Comment by saudet** [comment]
The supported way to get the "dtype" is with `TF_TensorType()`. We shouldn't try to access member variables directly unless we need to. They can go away at any time.

If you're trying to use binaries compiled for CUDA 10.2, you'll need to install CUDA 10.2 or add dependencies on the the redist artifacts here: http://repo2.maven.org/maven2/org/bytedeco/cuda/10.2-7.6-1.5.2/

**Comment by ShamsUlAzeem** [comment]
Hmm the one with javacpp 1.5.1 was: `10.1-7.6-1.5.1`

**Comment by saudet** [comment]
That one's for CUDA 10.1 Update 1: https://github.com/bytedeco/javacpp-presets/tree/1.5.1/cuda

**Comment by ShamsUlAzeem** [comment]
Ah right thanks. Let me give it a shot with that

**Comment by saudet** [comment]
And the one in 1.5.2 is for CUDA 10.1 Update 2: https://github.com/bytedeco/javacpp-presets/tree/1.5.1/cuda

**Comment by saudet** [comment]
But you might as well go with CUDA 10.2. There's no reason to use previous versions.

**Comment by ShamsUlAzeem** [comment]
Yeah true. One reason I can think of is for user adoption. If they have 10.1 already installed then it's some work for them to download and install a new cuda version

**Comment by saudet** [comment]
No, users don't need to install anything. They can use the redist artifacts. That's what they are for.

**Comment by agibsonccc** [comment]
That is what @farizrahman4u was working on.

**Comment by farizrahman4u** [comment]
@agibsonccc just like python exec, I think konduit should use nd4j's graphrunner once the snapshots are up.

**Comment by maxpumperla** [comment]
@agibsonccc @farizrahman4u there seem to be some differences between the `GraphRunner` versions. konduit checks for `TF_TensorType` for instance. that's why I was asking Adam how much they differ and if we can switch. I'd rather not do double-maintenance here, too.

**Comment by farizrahman4u** [comment]
@maxpumperla they shouldnt differ much at all, because I just ported GraphRunner from konduit to dl4j: https://github.com/KonduitAI/deeplearning4j/tree/master/nd4j/nd4j-tensorflow/src/main/java/org/nd4j/tensorflow/conversion

Changes include `.dtype()` -> `TF_TensorType` and couple of other fixes.

**Comment by maxpumperla** [comment]
@farizrahman4u ah, perfect. I was looking at the eclipse repo again. :D

**Comment by agibsonccc** [comment]
@sshepel are the snapshots for the recent merges with fariz's changes merged now?

**Pull request merged**
