### PR TITLE
WordPiece Tokenizer Preprocessing Step

### PR DESCRIPTION
**Pull request by chiaweilim**
The custom step is to return tokens from [BertIterator](https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/iterator/BertIterator.java)

Changes as per https://github.com/KonduitAI/konduit-serving/pull/241

1. Copyright header [WordTokenizerStepRunner.java](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/konduit-serving-core/src/main/java/ai/konduit/serving/pipeline/steps/WordTokenizerStepRunner.java#L4) [WordTokenizerStep.java](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/konduit-serving-api/src/main/java/ai/konduit/serving/pipeline/step/WordTokenizerStep.java#L4)

2. Bert Step changed to [WORD_TOKENIZER](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/python/konduit/load.py#L197)
Figured WORD_PIECE_TOKENIZER was rather long name (I can fix it if this is preferable)

3. Simple [test ](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/python/tests/test_word_tokenizer_step.py)and [yaml](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/python/tests/yaml/konduit_word_tokenizer_minimal.yaml) file added.

Questions: 
1. Is it okay if I assume using BertIterator is for [FIXED_LENGTH](https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/iterator/BertIterator.java#L132-L134)  & classification problem? I have  added a variable in yaml to change the [SENTENCE_MAX_LEN ](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/konduit-serving-core/src/main/java/ai/konduit/serving/pipeline/steps/WordTokenizerStepRunner.java#L84)for now.
2. Currently yaml returns 2 [NDArrays ](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/python/tests/yaml/konduit_word_tokenizer_minimal.yaml#L21-L22)- 1 for feature another for feature masks. Yet to test this yet, does this works if the intention is to pass in to DL4J LSTM model?

Pending work: Have not tested the latter step of passing in a model for results due to [#269](https://github.com/KonduitAI/konduit-serving/issues/269)

### CODE REVIEW

**Comment by chiaweilim** [comment]
Got this working for two step config file for sequence classification
1. Get tokens from text sequence  
2. Run inferences on the tokens with DL4J LSTM  
Client and config file in [here](https://github.com/codenamewei/konduit-serving-use-cases/tree/master/3-3-DL4J-LSTMTextClassification-MultiSteps)
The model & data file are in [Google Drive](https://drive.google.com/drive/u/3/folders/1G1n8tfNHuSJicmUCbtdCU9L0tXr6KiBh). 
Running Example: [gist](https://gist.github.com/chiaweilim/1c69cc5fc9902af3463f5f91a2754cb3)

One change i had to made was to [initializeSchema](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/PipelineRouteDefiner.java#L688-L704)
Before the changes, the steps were detecting second step schema when converting the first step output leading to errors. 

Have also added test to [here](https://github.com/chiaweilim/konduit-serving/blob/cw_bert_custom_step/python/tests/test_word_tokenizer_step.py)



let me know if changes needed.

**Comment by AlexDBlack** [comment]
> Bert Step changed to WORD_TOKENIZER
> Figured WORD_PIECE_TOKENIZER was rather long name (I can fix it if this is preferable)

Yeah, this should be referred to as WordPieceTokenizer etc - it refers to a very specific algorithm called "WordPiece" - whereas calling it simply "word tokenizer" arguably refers to a whole class of algorithms, not a specific algorithm.

**Comment by chiaweilim** [comment]
@AlexDBlack thanks for the update.
I will fix this today to WordPieceTokenizerStep and comment again once done.

**Comment by chiaweilim** [comment]
Did the changes. @AlexDBlack

**Comment by ShamsUlAzeem** [comment]
Yup looks good to me. Let's merge. Otherwise if @chiaweilim wants to write tests then this is helpful to find out the lines that needs to be covered. https://sonarcloud.io/component_measures?id=ai.konduit.serving%3Akonduit-serving&pullRequest=270&metric=new_coverage&view=list

Can be more than 80% if just `WordPieceTokenizerStep.java` and `WordPieceTokenizerStepRunner.java` are covered. Let me know if I can help with that.

**Comment by chiaweilim** [comment]
@ShamsUlAzeem it would be great if you can help...I'll learn from you and do a better coverage for test next time. Thanks.

**Comment by chiaweilim** [comment]
@ShamsUlAzeem Hi Shams, I've added tests to improve the code coverage. Let me know if any changes needed. Else, I don't mind for it to merge as I'm pretty much done with the PR. Thanks

**Comment by ShamsUlAzeem** [comment]
Looks good. @AlexDBlack let's merge?

**Pull request merged**
