### PR TITLE
[OLD API] Ability to create CustomStep from python and yaml

### PR DESCRIPTION
**Pull request by ShamsUlAzeem**
You can create a Custom Step from yaml like this:

`custom_step.yaml` file:
```
serving:
  http_port: 1337
steps:
  custom_step_one:
    type: CUSTOM
    custom_udf_clazz: <class_name>
client:
  port: 1337
```

From the server code side:
```
file_path = "custom_step.yaml"
server = server_from_file(file_path=file_path, start_server=True)
```

Remember to put the jar containing the extra class in the classpath of the server: #197

### CODE REVIEW

**Comment by agibsonccc** [comment]
@ShamsUlAzeem mind resolving conflicts?

**Comment by ShamsUlAzeem** [comment]
@agibsonccc solved them just now. @wmeddie @kmotohas can you confirm the working of this step through yaml based on your requirements before? IIRC we wanted to make a bert preprocessors with this.

**Comment by kmotohas** [comment]
Is there any existing code that I could refer to for `custom_udf_clazz`?
Is something like JAR file of DataVec's TransformProcess supposed to be `custom_udf_clazz`?

**Comment by wmeddie** [comment]
I added what I *think* it should look like here: https://github.com/wmeddie/custom-konduit-step Can someone give it a shot?

**Comment by wmeddie** [comment]
I think the PR as is is great, but after going through the exercise of making a custom UDF, we need to add some more functionality to UDF configuration before we can expect it to be usable in the real world.  The main issues here:

1. Figuring out what record this UDF is meant to work on.
2. Configuring the UDF.

For 1, the UDF gets a Record[] as input, but it had no idea which record it should be working on (except in the trivial case when there's only 1 record.)  We should pass the same schema configuration to the custom UDF constructor so that the UDF author can use that information to determine the proper index to use for input and output.  (Probably worth adding some helper methods on the base class to make it trivial.)

For 2 I think it'd be best if we can just pass a Map<String, String> to the UDF constructor for every other key inside the json or yaml file that isn't part of the standard schema config.  For example, this is necessary if I have two instances of the same UDF in a pipeline but they should use different vocabulary files.

**Comment by agibsonccc** [comment]
@wmeddie remember, the record array is not actually more than 1 record. More than 1 is actually not possible. It's only 1 record per input name.

**Comment by wmeddie** [comment]
Is this understanding correct?:
the batch -> Record[] (the parameter to the udf method)
the inputs -> records[0].getRecord()
input named "a" -> records[0].getRecord().get(0)
input named "b" -> records[0].getRecord().get(1)

**Comment by agibsonccc** [comment]
No:
"a": record[0]
"b": record[1]

**Comment by ShamsUlAzeem** [comment]
@agibsonccc I believe eduardo is right here... the mapping is done within a single record. In case of the bert network test here: https://github.com/KonduitAI/konduit-serving/blob/c0d550b9935ef2794b77bdba20f8aa007616e68e/python/tests/test_bert_serving.py

the record will look like:
Record[0] = [NDArrayWritable, NDArrayWritable, NDArrayWritable] -> ["IteratorGetNext:0", "IteratorGetNext:1", "IteratorGetNext:4"]

**Comment by agibsonccc** [comment]
@ShamsUlAzeem mind updating this?

**Comment by AlexDBlack** [comment]
@ShamsUlAzeem where is this at?
Seems like a reasonable feature to have, so it would be nice to get this wrapped up...

**Comment by ShamsUlAzeem** [comment]
Hmm have to think about how to add extra configuration options in there. Shouldn't be too hard to do. I'll come to this

**Comment by ShamsUlAzeem** [comment]
Closing due to becoming old api

**Pull request closed without merging**
