### PR TITLE
Fixing JSON configuration errors from minimized yaml config

### PR DESCRIPTION
**Pull request by ShamsUlAzeem**
Fixing #269

### CODE REVIEW

**Comment by ShamsUlAzeem** [comment]
@chiaweilim have to write tests for the yaml files but this should fix the model loading errors. Also, I've fixed the errors for showing exceptions if a similar error happens. 

Just update your build jars and python package and try again and let me know if it has worked for you.

**Comment by chiaweilim** [comment]
ok thanks, looking into this now.

**Comment by chiaweilim** [comment]
i able to test Keras & DL4J models loading good for now, yet I see timeout when calling the server for inference. 
Will check more and get back on this hopefully by today.

**Comment by ShamsUlAzeem** [comment]
Great. I'll see what's happening at inferences

**Comment by ShamsUlAzeem** [comment]
Are you calling through the `numpy-predict` CLI call or using the python API?

**Comment by chiaweilim** [comment]
im calling from konduit api build from python directory. 
testing on [https://github.com/codenamewei/konduit-serving-use-cases/tree/master/3-1-DL4J-HelloWorld/CSVClassifierServing](url)

**Comment by ShamsUlAzeem** [comment]
Thanks Chiawei. I've fixed the logging issues in both the python package and the main java application. Can you build the uberjar and python package and try again? 

Also, can I have access to the https://github.com/codenamewei/konduit-serving-use-cases repo? I have done some cleanup in the configuration and yaml file.

Also, the correct input should be a rank 2 array here: https://github.com/codenamewei/konduit-serving-use-cases/blob/master/3-1-DL4J-HelloWorld/CSVClassifierServing/konduit_cli_client.py#L30. So, `[[0.272702493273322,0.0201936700818061]]` instead of `[0.272702493273322,0.0201936700818061]` (notice the extra square bracket).

Also, verify if you can access the `/logs` endpoint

**Comment by chiaweilim** [comment]
Here's the invite to [https://github.com/codenamewei/konduit-serving-use-cases/invitations](https://github.com/codenamewei/konduit-serving-use-cases/invitations)

I'll check the rest soon. Thanks for the help.

**Comment by chiaweilim** [comment]
@ShamsUlAzeem 

i tried the uberjar and python package. It's working fine now. 

Also able to get inference results and logs at endpoint /logs

and yes, the input should be a rank 2 array. Thank you.

**Comment by ShamsUlAzeem** [comment]
Awesome!!

**Pull request merged**
